config: Branch logic updated

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -34,20 +34,45 @@ echo  "\n${NC}"
 local_branch="$(git rev-parse --abbrev-ref HEAD)"
 
 validate_branch_name() {
+    local numvar=3
     local branch_name="$1"
-    local pattern="^[A-Z]+_\d+_[a-z_]+$"
-    local ignore_list="main"
+    # local pattern="^[A-Z]+_\d+_[a-z_]+$"
+    local pattern="^[a-z_]+$"
+    local ignore_list="main" 
+      your_string_variable="login_module"
+
+#       regex_pattern="^[a-z_]+$"
+# echo "String with special characters: '$your_string_variable'"
 
      if [[ $branch_name == "main"  || $branch_name == "qa" || $branch_name == "uat" || $branch_name == "dev" ]]; then
         echo -e "${GREEN} Success: ${NC}  Branch name ${BLUE} '$branch_name'${NC} matches the pattern. \n\n" 
+        # exit 1
     elif [[ $branch_name =~ $pattern ]]; then
-        echo -e "${GREEN} Success: ${NC}  The condition is false  ${BLUE} \n\n"
-   
+        echo -e "${GREEN} Success: ${NC}   Branch name ${BLUE} '$branch_name'${NC} matches the pattern. \n\n" 
+        # exit 1
     else
         echo -e " ${RED} Error : ${NC}  Branch name ${BLUE} '$branch_name' ${NC} does not match the pattern \n\n"
         exit 1
 
     fi
+    # if [[ $your_string_variable =~ $regex_pattern ]]; then
+    #       echo "The variable contains '3'."
+    #       exit 1
+    # else
+    #     echo "The variable does not contain '3'."
+    #     exit 1
+    # fi
+    # if [[ $numvar == $ignore_list ]]; then
+    #     echo "Branch name '$branch_name' is in the ignore list."
+    # elif [[ $branch_name =~ $pattern ]]; then
+    #     echo "Branch name '$branch_name' matches the pattern."
+    # else
+    #     echo "Error: Branch name '$branch_name' does not match the pattern."
+    #     exit 1
+    # fi
+
+
+   
 }
 echo  "\n${NC}" 
 
